---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
spec:
  compression:
    compressor: zstd
  mover:
    cache:
      capacity: ${KOPIUR_CAPACITY:=5Gi}
      mode: Persistent
      storageClassName: miroir-replicated
    securityContext:
      runAsUser: ${KOPIUR_PUID:=1000}
      runAsGroup: ${KOPIUR_PGID:=1000}
  repository:
    kind: ClusterRepository
    name: expanse
  retention:
    keepLatest: 3
    keepHourly: 24
    keepDaily: 7
    keepWeekly: 4
  sources:
    - pvc:
        name: ${APP}
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=csi-ceph-blockpool}
