---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-repository
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kopiur-repository-secret
    template:
      data:
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
        KOPIA_SFTP_KEY_DATA: "{{ .KOPIA_SFTP_KEY_DATA }}"
        KOPIA_SFTP_KNOWN_HOSTS: "{{ .KOPIA_SFTP_KNOWN_HOSTS }}"
  dataFrom:
    - extract:
        key: kopiur
