[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }

_.file = ["{{config_root}}/.secrets.env"]
KUBECONFIG = "{{config_root}}/kubeconfig"
TALOSCONFIG = "{{config_root}}/talosconfig"
JUST_UNSTABLE = "1"
LEFTHOOK_OUTPUT = "false"

[tools]
"github:postfinance/topf" = "0.4.0-rc.0"
"aqua:helmfile/vals" = "v0.44.0"

[hooks]
postinstall = "lefthook install"
