---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chaski
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: chaski-secret
    template:
      data:
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        RADARR_PUSHOVER_TOKEN: "{{ .RADARR_PUSHOVER_TOKEN }}"
        SONARR_PUSHOVER_TOKEN: "{{ .SONARR_PUSHOVER_TOKEN }}"
  dataFrom:
    - extract:
        key: radarr
    - extract:
        key: sonarr
    - extract:
        key: pushover
