---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kopiur-system

components:
  - ../../components/alerts
  - ../../components/kopiur/secret

resources:
  - ./namespace.yaml
  - ./kopiur/ks.yaml
