---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/groupsnapshot.storage.k8s.io/volumegroupsnapshotclass_v1.json
apiVersion: groupsnapshot.storage.k8s.io/v1
kind: VolumeGroupSnapshotClass
metadata:
  name: miroir
driver: miroir.home-operations.com
deletionPolicy: Delete
