---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dufs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dufs-secret
    template:
      data:
        DUFS_AUTH: admin:{{ .ADMIN_PASSWORD }}@/:rw|flate:{{ .FLATE_PASSWORD }}@/flate:rw|@/flate
  dataFrom:
    - extract:
        key: dufs
