---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: konflate
spec:
  chartRef:
    kind: OCIRepository
    name: konflate
  interval: 1h
  values:
    config:
      repo: github://onedr0p/home-ops
      statusChecks: true
      prComments: true
      publicUrl: https://{{ .Release.Name }}.turbo.ac
      mcp: true
    secret:
      existingSecret: konflate-webhook-token-secret
    httpRoute:
      enabled: true
      annotations:
        gatus.home-operations.com/endpoint: |-
          conditions: ["[STATUS] == 200"]
      parentRefs:
        - name: envoy-external
          namespace: network
      hostnames:
        - "{{ .Release.Name }}.turbo.ac"
    monitoring:
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 50m
      limits:
        memory: 1Gi
