---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-operations-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk-home-operations
  target:
    name: home-operations-runner-secret
  data:
    - secretKey: github_app_id
      remoteRef:
        key: actions-runner/ACTIONS_RUNNER_APP_ID
    - secretKey: github_app_installation_id
      remoteRef:
        key: actions-runner/ACTIONS_RUNNER_INSTALLATION_ID
    - secretKey: github_app_private_key
      remoteRef:
        key: actions-runner/ACTIONS_RUNNER_PRIVATE_KEY
