---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-operations-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-operations-runner-secret
    template:
      data:
        github_app_id: "{{ .STICKY_GECKO_APP_CLIENT_ID }}"
        github_app_installation_id: "{{ .STICKY_GECKO_APP_INSTALLATION_ID }}"
        github_app_private_key: "{{ .STICKY_GECKO_APP_PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: sticky-gecko
