---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-sdk-home-operations
spec:
  provider:
    onepasswordSDK:
      vault: Shared
      auth:
        serviceAccountSecretRef:
          name: onepassword-sdk-home-operations-secret
          namespace: external-secrets
          key: token
