---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword-sdk-home-operations
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: onepassword-sdk-home-operations-secret
    template:
      data:
        token: "{{ .OP_SERVICE_ACCOUNT_TOKEN }}"
  dataFrom:
    - extract:
        key: onepassword-sdk
