---
cluster:
  allowSchedulingOnControlPlanes: true
  coreDNS:
    disabled: true
  etcd:
    advertisedSubnets:
      - 192.168.42.0/24
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
  apiServer:
    auditPolicy:
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
        - level: Metadata
    certSANs:
      - k8s.internal
    disablePodSecurityPolicy: true
    admissionControl:
      - name: PodSecurity
        $patch: delete
    extraArgs:
      enable-aggregator-routing: "true"
      feature-gates: HPAScaleToZero=true
  controllerManager:
    extraArgs:
      bind-address: 0.0.0.0
      feature-gates: HPAScaleToZero=true
  proxy:
    disabled: true
  scheduler:
    config:
      apiVersion: kubescheduler.config.k8s.io/v1
      kind: KubeSchedulerConfiguration
      profiles:
        - schedulerName: default-scheduler
          plugins:
            score:
              disabled:
                - name: ImageLocality
          pluginConfig:
            - name: PodTopologySpread
              args:
                defaultingType: List
                defaultConstraints:
                  - maxSkew: 1
                    topologyKey: kubernetes.io/hostname
                    whenUnsatisfiable: ScheduleAnyway
    extraArgs:
      bind-address: 0.0.0.0
machine:
  features:
    kubernetesTalosAPIAccess:
      enabled: true
      allowedKubernetesNamespaces:
        - actions-runner-system
        - system-upgrade
      allowedRoles:
        - os:admin
  nodeLabels:
    topology.kubernetes.io/zone: m
