---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: &name home-ops-runner
spec:
  endpointSelector:
    matchLabels:
      runner: *name
  enableDefaultDeny:
    egress: false
  egressDeny:
    - toCIDRSet:
        - cidr: 10.0.0.0/8
          except:
            - 10.42.0.0/16
            - 10.43.0.0/16
    - toCIDR:
        - 172.16.0.0/12
    - toCIDRSet:
        - cidr: 192.168.0.0/16
          except:
            - 192.168.42.0/24
