---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/tuppr.home-operations.com/talosupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
spec:
  talos:
    # renovate: datasource=custom.talos-factory depName=siderolabs/talos
    version: v1.13.6
  policy:
    rebootMode: powercycle
  silences:
    - matchers:
        - name: alertname
          value: ^(CephDaemonSlowOps|CephHealthWarning|CephMonDown|CephMonDownQuorumAtRisk|CephOSDDown|CephOSDDownHigh|CephOSDHostDown|CephSlowOps|KubeNodeEviction|KubeNodeNotReady|KubeNodeReadinessFlapping|KubeNodeUnreachable|TargetDown)$
          matchType: "=~"
  healthChecks:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Snapshot
      expr: |-
        status.phase != 'Running'
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Restore
      expr: |-
        !(status.phase in ['Resolving', 'Restoring'])
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      expr: |-
        status.ceph.health in ['HEALTH_OK']
