---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: towonel-agent
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  endpoints:
    - dnsName: external.turbo.ac
      recordType: CNAME
      targets:
        - edge-na.towonel.dev
