---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: deduparr
spec:
  chartRef:
    kind: OCIRepository
    name: deduparr
  interval: 1h
  values:
    controllers:
      deduparr:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: quay.io/kernald/deduparr
              tag: 1.2.0@sha256:6e579f684a147dcd2dcd4468c50ffb0848e23b8306f1355037a2419931fe4b7f
            env:
              DEDUPARR_LOG_LEVEL: info
              DEDUPARR_RADARR_MOVIES_ENABLED: true
              DEDUPARR_RADARR_MOVIES_URL: http://radarr.default.svc.cluster.local
              DEDUPARR_REMOVE_FROM_CLIENT: false
              DEDUPARR_SCHEDULE: service
              DEDUPARR_SERVICE__INTERVAL: 2m
              DEDUPARR_SERVICE__PORT: &port 80
              DEDUPARR_SONARR_SERIES_ENABLED: true
              DEDUPARR_SONARR_SERIES_URL: http://sonarr.default.svc.cluster.local
              TZ: America/New_York
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health/ready
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        endpoints:
          - port: http
