---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kritika-postgres-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kritika-postgres-credentials
    template:
      type: kubernetes.io/basic-auth
      data:
        username: kritika
        password: "{{ .KRITIKA_POSTGRES_OWNER_PASSWORD }}"
        uri: "postgres://kritika:{{ .KRITIKA_POSTGRES_OWNER_PASSWORD }}@kritika-postgres-rw:5432/kritika?sslmode=require&connect_timeout=10"
  dataFrom:
    - extract:
        key: kritika
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kritika-postgres-app
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kritika-postgres-app
    template:
      type: kubernetes.io/basic-auth
      data:
        username: kritika_app
        password: "{{ .KRITIKA_POSTGRES_APP_PASSWORD }}"
        uri: "postgres://kritika_app:{{ .KRITIKA_POSTGRES_APP_PASSWORD }}@kritika-postgres-rw:5432/kritika?sslmode=require&connect_timeout=10"
  dataFrom:
    - extract:
        key: kritika
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kritika-postgres-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kritika-postgres-runner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: kritika_runner
        password: "{{ .KRITIKA_POSTGRES_RUNNER_PASSWORD }}"
        uri: "postgres://kritika_runner:{{ .KRITIKA_POSTGRES_RUNNER_PASSWORD }}@kritika-postgres-rw:5432/kritika?sslmode=require&connect_timeout=10"
  dataFrom:
    - extract:
        key: kritika
