---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./database.yaml
  - ./databaserole.yaml
  - ./externalsecret.yaml
  - ./podmonitor.yaml
