---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect-home-operations
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect-home-operations.external-secrets.svc.cluster.local
      vaults:
        Shared: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-home-operations-vault-secret
            namespace: external-secrets
            key: OP_CONNECT_TOKEN
