---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect-home-operations
spec:
  chartRef:
    kind: OCIRepository
    name: onepassword-connect-home-operations
  interval: 1h
  values:
    connect:
      applicationName: onepassword-connect-home-operations
      host: onepassword-connect-home-operations
      annotations:
        reloader.stakater.com/auto: "true"
      api:
        httpPort: 80
        imageRepository: ghcr.io/1password/connect-api
        serviceMonitor:
          enabled: true
      credentialsName: onepassword-connect-home-operations-credentials-secret
      sync:
        imageRepository: ghcr.io/1password/connect-sync
