---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword-connect-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: onepassword-connect-credentials-secret
    template:
      data:
        1password-credentials.json: '{{ .OP_CREDENTIALS_JSON }}'
  dataFrom:
    - extract:
        key: 1password
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword-connect-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: onepassword-connect-vault-secret
    template:
      data:
        token: '{{ .OP_CONNECT_TOKEN }}'
  dataFrom:
    - extract:
        key: 1password
