---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
spec:
  chartRef:
    kind: OCIRepository
    name: onepassword-connect
  interval: 1h
  values:
    connect:
      annotations:
        reloader.stakater.com/auto: "true"
      api:
        httpPort: 80
        imageRepository: ghcr.io/1password/connect-api
        serviceMonitor:
          enabled: true
      sync:
        imageRepository: ghcr.io/1password/connect-sync
  postRenderers:
    - # NOTE: Instead of having the credentials mounted as a file, we can set them as an environment variable.
      # This is because on bootstrap kustomize strips quotes around the JSON in stringData values, which makes
      # the value a JSON object instead of a string. Instead of having the secret contain raw JSON we just use
      # the base64 encoded value of the JSON in onepassword-connect-credentials-secret which avoids the issue.
      kustomize:
        patches:
          - target:
              kind: Deployment
              name: onepassword-connect
            patch: |-
              - op: remove
                path: /spec/template/spec/containers/0/env/0
              - op: remove
                path: /spec/template/spec/containers/1/env/1
              - op: add
                path: /spec/template/spec/containers/0/envFrom
                value:
                  - secretRef:
                      name: onepassword-connect-credentials-secret
              - op: add
                path: /spec/template/spec/containers/1/envFrom
                value:
                  - secretRef:
                      name: onepassword-connect-credentials-secret
              - op: remove
                path: /spec/template/spec/containers/0/volumeMounts/1
              - op: remove
                path: /spec/template/spec/containers/1/volumeMounts/1
              - op: remove
                path: /spec/template/spec/volumes/1
