---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: brrpolice
spec:
  chartRef:
    kind: OCIRepository
    name: brrpolice
  interval: 1h
  values:
    controllers:
      brrpolice:
        containers:
          app:
            image:
              repository: ghcr.io/zariel/brrpolice
              tag: v0.12.1@sha256:dfad36b5de5b49c2180dbe45d04e52d7b3681d27987a8780d6306e8455d8b1d2
            env:
              BRRPOLICE_HTTP__PORT: &port 80
              BRRPOLICE_LOGGING__LEVEL: info
              BRRPOLICE_QBITTORRENT__BASE_URL: http://qbittorrent.default.svc.cluster.local
              TZ: America/New_York
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        endpoints:
          - port: http
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
