---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unifi-dns
spec:
  chartRef:
    kind: OCIRepository
    name: unifi-dns
  interval: 1h
  values:
    fullnameOverride: *app
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/home-operations/external-dns-unifi-webhook
          tag: 0.10.4@sha256:ffb5dab38e52f8eaa714dd9e9e43575cd2cac7f68191b2d077940f13e397bed7
        env:
          - name: UNIFI_HOST
            value: https://unifi.internal
          - name: UNIFI_API_KEY
            valueFrom:
              secretKeyRef:
                name: &secret unifi-dns-secret
                key: UNIFI_API_KEY
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
    triggerLoopOnEvent: true
    policy: sync
    sources:
      - gateway-httproute
      - service
    txtOwnerId: main
    txtPrefix: k8s.main.%{record_type}-
    domainFilters:
      - turbo.ac
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
