[env]
FLATE_PATH = '{{config_root}}/kubernetes/flux/cluster'
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/talosconfig"
JUST_UNSTABLE = "1"

[hooks]
postinstall = "lefthook install"

[tools]
"1password-cli" = "2.35.0"
actionlint = "1.7.12"
"github:mitsuhiko/minijinja" = "2.24.0"
jq = "1.8.2"
just = "1.58.0"
lefthook = "2.1.10"
node = "26.7.0"
oxfmt = "0.64.0"
shellcheck = "0.11.0"
talos = "1.14.0-beta.1"
yq = "4.53.6"
zizmor = "1.29.0"
