---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/generators.external-secrets.io/password_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: zwave
spec:
  length: 64
  symbols: 0
  allowRepeat: true
  noUpper: false
  secretKeys:
    - SESSION_SECRET
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zwave
spec:
  refreshPolicy: CreatedOnce
  target:
    name: zwave-secret
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: zwave
