---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: ${APP}-dragonfly
spec:
  replicas: 2
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: ${APP}-dragonfly
  authentication:
    passwordFromSecret:
      name: ${APP}-dragonfly-secret
      key: password
  snapshot:
    cron: "*/5 * * * *"
    persistentVolumeClaimSpec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: miroir-slow
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  args:
    - --dbfilename=dump
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
  resources:
    requests:
      cpu: 25m
    limits:
      memory: 512Mi
