---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-drivers
spec:
  chartRef:
    kind: OCIRepository
    name: ceph-csi-drivers
  interval: 1h
  values:
    drivers:
      cephfs:
        enabled: true
        name: rook-ceph.cephfs.csi.ceph.com
        snapshotPolicy: volumeGroupSnapshot
      nfs:
        enabled: false
      nvmeof:
        enabled: false
      rbd:
        enabled: true
        name: rook-ceph.rbd.csi.ceph.com
        snapshotPolicy: volumeGroupSnapshot
