---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: miroir
  labels:
    metrics: miroir
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: miroir
  podTargetLabels:
    - app.kubernetes.io/component
  podMetricsEndpoints:
    - port: metrics
