---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chorus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: chorus-secret
    template:
      data:
        config.yaml: |
          storage:
            storages:
              garage:
                credentials:
                  kopiur:
                    accessKeyID: "{{ .AWS_ACCESS_KEY_ID }}"
                    secretAccessKey: "{{ .AWS_SECRET_ACCESS_KEY }}"
              r2:
                address: "{{ .R2_ENDPOINT_URL }}"
                credentials:
                  kopiur:
                    accessKeyID: "{{ .R2_ACCESS_KEY_ID }}"
                    secretAccessKey: "{{ .R2_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: R2_ENDPOINT_URL
      remoteRef:
        key: kopiur-r2
        property: AWS_ENDPOINT_URL
    - secretKey: R2_ACCESS_KEY_ID
      remoteRef:
        key: kopiur-r2
        property: AWS_ACCESS_KEY_ID
    - secretKey: R2_SECRET_ACCESS_KEY
      remoteRef:
        key: kopiur-r2
        property: AWS_SECRET_ACCESS_KEY
  dataFrom:
    - extract:
        key: kopiur
