---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs-collector
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: victoria-logs-collector
  values:
    fullnameOverride: victoria-logs-collector
    global:
      image:
        registry: quay.io
    podMonitor:
      enabled: true
    remoteWrite:
      - url: http://victoria-logs.o11y.svc.cluster.local:9428
