---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kritika
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kritika-secret
    template:
      data:
        KRITIKA_AUTH_ADMIN_PASSWORD: "{{ .KRITIKA_ADMIN_PASSWORD }}"
        KRITIKA_PROVIDERS_API_KEY: "{{ .KRITIKA_OPENROUTER_API_KEY }}"
        KRITIKA_ANTHROPIC_API_KEY: "{{ .KRITIKA_ANTHROPIC_API_KEY }}"
        KRITIKA_GITHUB_CLIENT_ID: "{{ .GITHUB_BOT_APP_CLIENT_ID }}"
        KRITIKA_GITHUB_PRIVATE_KEY: "{{ .GITHUB_BOT_APP_PRIVATE_KEY }}"
        KRITIKA_GITHUB_WEBHOOK_SECRET: "{{ .GITHUB_BOT_APP_WEBHOOK_SECRET }}"
  dataFrom:
    - extract:
        key: kritika
    - extract:
        key: bot-vila-bot
