---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-metrics
  interval: 1h
  values:
    fullnameOverride: victoria-metrics
    crds:
      enabled: true
    admissionWebhooks:
      enabled: true
      certManager:
        enabled: true
    env:
      - name: VM_VMALERTDEFAULT_IMAGE
        value: quay.io/victoriametrics/vmalert
      - name: VM_VMAGENTDEFAULT_IMAGE
        value: quay.io/victoriametrics/vmagent
      - name: VM_VMSINGLEDEFAULT_IMAGE
        value: quay.io/victoriametrics/victoria-metrics
      - name: VM_VMCLUSTERDEFAULT_VMSELECTDEFAULT_IMAGE
        value: quay.io/victoriametrics/vmselect
      - name: VM_VMCLUSTERDEFAULT_VMSTORAGEDEFAULT_IMAGE
        value: quay.io/victoriametrics/vmstorage
      - name: VM_VMCLUSTERDEFAULT_VMINSERTDEFAULT_IMAGE
        value: quay.io/victoriametrics/vminsert
      - name: VM_VMBACKUP_IMAGE
        value: quay.io/victoriametrics/vmbackupmanager
      - name: VM_VMAUTHDEFAULT_IMAGE
        value: quay.io/victoriametrics/vmauth
      - name: VM_VMALERTMANAGER_ALERTMANAGERDEFAULTBASEIMAGE
        value: quay.io/prometheus/alertmanager
    image:
      registry: quay.io
    operator:
      enable_converter_ownership: true
    serviceMonitor:
      enabled: true
