---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-metrics
  interval: 1h
  values:
    fullnameOverride: victoria-metrics
    global:
      image:
        registry: quay.io
    crds:
      enabled: true
    operator:
      enable_converter_ownership: true
    serviceMonitor:
      enabled: true
