---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/apps/daemonset_v1.json
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kata-guest-kernel
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kata-guest-kernel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kata-guest-kernel
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
      initContainers:
        - name: install
          image: ghcr.io/home-operations/kata-guest-kernel:3.32.0
          volumeMounts:
            - name: host
              mountPath: /host/var/lib/kata-nested
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.10
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              memory: 32Mi
      volumes:
        - name: host
          hostPath:
            path: /var/lib/kata-nested
            type: DirectoryOrCreate
