{
 "title": "qBittorrent",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(qbittorrent_connected, service)"
    }
   },
   {
    "name": "categories",
    "label": "Categories",
    "query": {
     "query": "label_values(qbittorrent_torrents_count{service=\"$service\"}, category)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "qBittorrent Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "qbittorrent_up{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Bittorrent Network",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_connected{service=\"$service\"} - qbittorrent_firewalled{service=\"$service\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "DHT Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_dht_nodes{service=\"$service\"}",
     "legendFormat": "DHT nodes"
    }
   ]
  },
  {
   "title": "Data Downloaded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(qbittorrent_dl_info_data_total{service=\"$service\"}[100y])"
    }
   ]
  },
  {
   "title": "Data Uploaded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(qbittorrent_up_info_data_total{service=\"$service\"}[100y])"
    }
   ]
  },
  {
   "title": "Accumulated Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(qbittorrent_up_info_data_total{service=\"$service\"}[100y]) / increase(qbittorrent_dl_info_data_total{service=\"$service\"}[100y])"
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(qbittorrent_dl_info_data_total{service=\"$service\"}[1m])"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(qbittorrent_up_info_data_total{service=\"$service\"}[1m])"
    }
   ]
  },
  {
   "title": "Transfer Ratio",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(qbittorrent_dl_info_data_total{service=\"$service\"}[1m])",
     "legendFormat": "Download"
    },
    {
     "expr": "rate(qbittorrent_up_info_data_total{service=\"$service\"}[1m])",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Torrents by Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qbittorrent_torrents_count{category=~\"${categories}\", status!=\"complete\", service=\"$service\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Torrents by Categories",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(qbittorrent_torrents_count{category=~\"${categories}\",status!=\"complete\",service=\"$service\"}) by (category)",
     "legendFormat": "{{category}}"
    }
   ]
  }
 ]
}